### ISSUE TITLE
Website updates (for easier tracking)

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_win22_coursepage#1]
**Shorter term:**
- [x] Modify course dates to correspond to Winter '22. Can assume Tues/Thurs scheduling: https://rebeccajohnson88.github.io/qss20_win22_coursepage/docs/course_schedule.html
- [x] Modify title on first page from QSS20 to QSS20/PBPL 40.01 - https://rebeccajohnson88.github.io/qss20_win22_coursepage/docs/index.html
- [ ] Replace the TRLA SIP page with one based on this doc - https://docs.google.com/document/d/12l4pAn1LL9uuTB37Rfd8ojTMeRoYm2uIuDpZZ2bYFuY/edit 

**Longer term (just to keep track)**:

- Edit course schedule to reflect (1) pandas first and remove workflow, (2) earlier pset 1 part one, (3) other changes we discuss as course team
